# Generated by Django 5.1.6 on 2025-04-12 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0003_post_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_1',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='post_1',
            name='updated_at',
        ),
    ]
