# Generated by Django 5.1.6 on 2025-04-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_api', '0004_remove_post_1_created_at_remove_post_1_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_1',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='post_1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
